version: '3.9'

services:
   backend:
       container_name: backend
       build: ./backend
       ports: 
          - 3030:3030
   
   frontend:
       container_name: frontend
       build: ./frontend
       ports: 
         - 3000:3000
       depends_on: 
         - backend

# terminal command to start compose
# docker-compose up -d