version: '3.9'

services:
   backend:
       image: backend
       container_name: backend
       build: ./backend
       ports: 
          - 3030:3030
   
   frontend:
       image: frontend
       container_name: frontend
       build: ./frontend
       env_file:
        - .env
       ports: 
         - ${PORT}:${PORT}
       depends_on: 
         - backend

# terminal command to start compose
# docker-compose up -d