version: '3.9'

services:
  
   database:
     image: postgres
     restart: always
     environment: 
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: test
       POSTGRES_DB: example-database
     ports:
       - 5432:5432
     volumes:
       - .data:/var/lib/postgresql/data

   backend:
       image: backend
       container_name: backend
       build: ./backend
       ports: 
          - 3030:3030
       depends_on:
         - database
   
   frontend:
       image: frontend
       container_name: frontend
       build: ./frontend
       env_file:
        - .env
       ports: 
         - ${PORT}:${PORT} # Example with env variables
       depends_on: 
         - backend

# terminal command to start compose
# docker-compose up -d